# Generated by Django 5.2.6 on 2025-09-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название услуги"),
                ),
                (
                    "slug",
                    models.SlugField(
                        unique=True, verbose_name="URL-адрес (автоматически)"
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Скопируйте класс с сайта FontAwesome",
                        max_length=100,
                        verbose_name="Класс иконки (например, 'fa-solid fa-network-wired')",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Краткое описание"
                    ),
                ),
                (
                    "full_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Полное описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Изображение/баннер",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше услуга в списке",
                        verbose_name="Порядок сортировки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["sort_order"],
            },
        ),
    ]
