# Generated by Django 5.2.6 on 2025-09-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Краткое описание страницы для поисковых систем.",
                verbose_name="SEO Описание (Description)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Если не заполнено, будет использовано название услуги.",
                max_length=255,
                verbose_name="SEO Заголовок (Title)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="full_description",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Полное описание (для отдельной страницы)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Краткое описание (для карточки на главной)",
            ),
        ),
    ]
