# Generated by Django 5.2.6 on 2025-09-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_service_meta_description_service_meta_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="image",
        ),
        migrations.AddField(
            model_name="service",
            name="original_image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение. Оно будет автоматически обрезано и оптимизировано.",
                null=True,
                upload_to="services/originals/",
                verbose_name="Изображение для услуги",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="full_description",
            field=models.TextField(
                blank=True, verbose_name="Полное описание (для отдельной страницы)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="Скопируйте класс с сайта FontAwesome.",
                max_length=100,
                verbose_name="Класс иконки (например, 'fa-solid fa-network-wired')",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Краткое описание страницы для поисковиков (сниппет). Оптимальная длина ~ 150-160 символов. Если пусто, используется краткое описание услуги.",
                verbose_name="SEO Описание (Description)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Отображается во вкладке браузера и в заголовке поисковой выдачи. Оптимальная длина ~ 60 символов. Если пусто, используется название услуги.",
                max_length=255,
                verbose_name="SEO Заголовок (Title)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description",
            field=models.TextField(
                verbose_name="Краткое описание (для карточки на главной)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                help_text="Используется для создания красивых URL. Например, 'nastrojka-mikrotik'.",
                unique=True,
                verbose_name="URL-адрес (автоматически)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Чем меньше число, тем выше услуга в списке.",
                verbose_name="Порядок сортировки",
            ),
        ),
    ]
