# Generated by Django 5.2.6 on 2025-09-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_service_image_service_original_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок страницы (H1)"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Короткое имя для URL, например, 'about'. Должно быть уникальным.",
                        max_length=200,
                        unique=True,
                        verbose_name="URL (слаг)",
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("pages/default.html", "Универсальный шаблон"),
                            ("pages/about.html", "О компании"),
                            ("pages/contacts.html", "Контакты"),
                        ],
                        default="pages/default.html",
                        help_text="Выберите шаблон, который определяет внешний вид страницы.",
                        max_length=100,
                        verbose_name="Шаблон для отображения",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Содержимое страницы. Поддерживается Markdown.",
                        verbose_name="Основной контент",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть страницу с сайта.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Если не заполнено, будет использован основной заголовок страницы.",
                        max_length=200,
                        verbose_name="SEO Заголовок (Title)",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание страницы для поисковых систем.",
                        verbose_name="SEO Описание (Description)",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.page",
                        verbose_name="Родительская страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
                "ordering": ["slug"],
            },
        ),
    ]
