# Generated by Django 5.2.6 on 2025-09-14 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_page"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Используется в URL, например, /blog/category/network/",
                        max_length=100,
                        unique=True,
                        verbose_name="URL (слаг)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория блога",
                "verbose_name_plural": "Категории блога",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название тега"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Используется в URL, например, /blog/tag/mikrotik/",
                        max_length=100,
                        unique=True,
                        verbose_name="URL (слаг)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["slug"],
                "verbose_name": "Страницу",
                "verbose_name_plural": "Страницы",
            },
        ),
        migrations.AlterField(
            model_name="page",
            name="template",
            field=models.CharField(
                choices=[
                    ("core/pages/default.html", "Универсальный шаблон"),
                    ("core/pages/about.html", "О компании"),
                    ("core/pages/contacts.html", "Контакты"),
                ],
                default="core/pages/default.html",
                help_text="Выберите шаблон, который определяет внешний вид страницы.",
                max_length=100,
                verbose_name="Шаблон для отображения",
            ),
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок статьи"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL (слаг)"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Поддерживается Markdown.",
                        verbose_name="Содержимое статьи",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Поставьте галочку, чтобы опубликовать статью на сайте.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/originals/",
                        verbose_name="Изображение для статьи",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SEO Заголовок (Title)"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, verbose_name="SEO Описание (Description)"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="core.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="core.tag",
                        verbose_name="Теги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья блога",
                "verbose_name_plural": "Статьи блога",
                "ordering": ["-published_date"],
            },
        ),
    ]
