# Generated by Django 5.2.6 on 2025-09-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_category_slug_alter_tag_slug_article_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_date"],
                "verbose_name": "Статью",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория статей",
                "verbose_name_plural": "Категории статей",
            },
        ),
        migrations.AddField(
            model_name="page",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="service",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
